<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Atharva" failures="1" tests="3" name="testNgpack.VerifyUserSignUpPopUp" time="10.013" errors="0" timestamp="2023-08-28T13:29:30 IST" skipped="2">
  <testcase classname="testNgpack.VerifyUserSignUpPopUp" name="test" time="10.013">
    <failure message="expected [] but found [Enter the email address or mobile phone number associated with your Amazon account.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [] but found [Enter the email address or mobile phone number associated with your Amazon account.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testNgpack.VerifyUserSignUpPopUp.test(VerifyUserSignUpPopUp.java:107)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="testNgpack.VerifyUserSignUpPopUp" name="test123">
    <skipped/>
  </testcase> <!-- test123 -->
  <system-out/>
  <testcase classname="testNgpack.VerifyUserSignUpPopUp" name="test1234">
    <skipped/>
  </testcase> <!-- test1234 -->
  <system-out/>
</testsuite> <!-- testNgpack.VerifyUserSignUpPopUp -->
